version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8765:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - /var/wp-http:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /var/wp-db:/var/lib/mysql
